name: Deploy to web

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TARGET: 'web'

jobs:
  
  build:
    name: Build Kotlin/Wasm
    runs-on: ubuntu-latest
    steps:

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '24'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: List all files
        run: find .

      - name: Run Gradle build
        run: |
          chmod +x gradlew
          ./gradlew build allTests wasmJsBrowserDistribution

      - name: Fix permissions
        run: |
          chmod -v -R +rX "app/build/dist/wasmJs/productionExecutable/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Rename
        run: |
          mv app/build/dist/wasmJs/productionExecutable app/build/dist/wasmJs/oni-seed-browser

      - name: Deploy over FTP
        uses: modern-dev/ftp-mirror@v2
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "app/build/dist/wasmJs/oni-seed-browser"
          remote_dir: "/httpdocs/oni-seed-browser/"
          delete: true

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_DEPLOYMENT_TOKEN }}
          action: "upload"
          app_location: "app/build/dist/wasmJs/oni-seed-browser"
          output_location: ""
          skip_app_build: true
